### ISSUE TITLE
Do we need an `instance Exception (HttpDecodeError String)`?

### ISSUE THREAD

**Issue by StevenXL** [freckle/frontrow-app#2]
We have an `instance Exception e => Exception (HttpDecodeError e) where`, but `httpJson` specializes the `e` to `String`, and string is not an instance of `Exception`.

This leads to an issue where we can't use `getResponseBodyUnsafe` with `httpJson` because `HttpDecodeError e`, where `e ~ String` is not an instance of Exception.

OR, I could totally be missing something obvious.

**Comment by pbrisbin** [comment]
This was a total mistake and corrected in bc69697e6a6fa5a2541442fa32733795dc3d3d18
